### ISSUE TITLE
Use of deprecated methods in examples?

### ISSUE THREAD

**Issue by enckse** [D-Programming-Deimos/ZeroMQ#23]
I was trying to get some ZMQ stuff working in dlang and noticed that the code in zmq.d is indicated as deprecated for some of the methods used in the examples within this repo.

```
/*  Deprecated methods */
int zmq_device(int type, void* frontend, void* backend);
int zmq_sendmsg(void* s, zmq_msg_t* msg, int flags);
int zmq_recvmsg(void* s, zmq_msg_t* msg, int flags);
```

seems like the examples should use zmq_msg_recv and zmq_msg_send if those methods are really deprecated? More than willing to update the examples myself but wanted clarification

**Comment by CyberShadow** [comment]
According to the README, the D examples are translated from the examples in the ZeroMQ documentation, so it might be worth checking if their documentation has updated examples.

**Comment by enckse** [comment]
I didn't see the usage of zmq_sendmsg/zmq_recvmsg on the zeromq examples page. The examples in this repo haven't been touched in a while and I don't know when those methods were deprecated and/or what the examples page looked like when they were translated.

Not that the uses change that much over time but as someone who has done zeromq in multiple languages and this is my first attempt in D, I'm struggling to find a good, functional example as well...hopefully what I write I can put on github and provide further zmq usage in D.

Anyone looking at this, if there is/are more extensive examples I'm just not seeing _please_ alert me

**Comment by kyllingstad** [comment]
I'm the one who's been maintaining these bindings in recent years, and I admit I haven't done anything with the examples, only the header files. Actually, I think the `examples/` subdirectory should just be removed. `zmq.d` only contains prototypes for the libzmq C functions, so the examples in the ZeroMQ documentation ought to do just fine without us maintaining D versions in parallel here.

If you're looking for a more "D-ish" interface to ZeroMQ, may I shamelessly suggest that you have a look at my wrapper library, [zmqd](https://github.com/kyllingstad/zmqd)? It even has up-to-date examples (I hope!).

**Comment by enckse** [comment]
Thanks @kyllingstad 

This isn't meant to be a critique of this project or dlang itself but it's...often hard to find the "D way" of doing something (e.g. zeromq). So when I'm hunting around trying to figure out which zmq library in D is the right one and multiple are listed by the source material itself (e.g. http://zeromq.org/bindings:d) and then I sort of do some more analysis and end up here but...now I don't know if someone has written abstraction layer (as you have) or if I just...either have to write one myself or accept just doing the C-bindings. This got a bit rant-y (which I didn't want, I really like D - this has happened to me in multiple places trying to implement something I've done in other languages in the past) but I want to advocate for people to use D but when it takes me a morning to go from 0 to zeromq REQ/REP implementation because I don't know what lib, examples, or documentation to use...it can be frustrating.

I guess to summarize my above comment: if we remove the `examples/` we're dropping people into direct C-bindings (which, honestly, I don't want to deal with and wouldn't ask of someone else either) unless we link to something like your wrapper? If I can be of use in anyway in this regard, please let me know.
