### ISSUE TITLE
ZMQ_ROUTER sockets do not receive any messages

### ISSUE THREAD

**Issue by Web-eWorks** [D-Programming-Deimos/ZeroMQ#26]
On Solus Linux, with system-level ZeroMQ 4.2.2, a ZMQ_ROUTER type socket will not receive any messages, simply blocking forever.  I tested it with both this binding and zmqd, and tried different combinations of req/dealer->rep/router, and consistently only the router socket was having any trouble.

If it makes any difference, the server and client are in separate D Threads, launched from the main thread.  I tried both zmqd's global context and a manually created context from `zmq_ctx_new`.

To confirm, I compiled a few of ZeroMQ's C examples, and they function as expected.
I also created a local version 4.2.2, replacing the headers in the binding's C directory with the system-wide headers, and compiled my test program against that, to no avail.

EDIT: Also tested on latest master, to no effect.

**Comment by kyllingstad** [comment]
Thanks for reporting!

Most likely, this is simply because we haven't updated these bindings to ZeroMQ v4.2 yet, and I would guess that the ZeroMQ people have introduced (yet another) change that breaks ABI incompatibility between minor versions.

I'll try to get around to updating to 4.2 this weekend.

**Comment by kyllingstad** [comment]
Sorry, my bad, we *have* updated to 4.2, I've simply forgotten to add the appropriate tags. Then I'll have to look more closely into it.

**Comment by kyllingstad** [comment]
Sorry for the (long) delay, but I finally got around to looking into this now. Unfortunately, I haven't figured out why there should be a problem specifically with the D bindings and not the equivalent C code. Do you have a test case you can post here?

Btw., I just submitted a pull request (#27) that updates the bindings to version 4.2.2 and also fixes some small bugs from a previous update. You should try and see if that version fixes your problem.

**Comment by Web-eWorks** [comment]
Using `zmqd`, here's a test case.

```
import std.stdio, zmqd, core.thread;

void main()
{
    void _thread() {
        auto req = Socket(SocketType.req);

        req.connect("tcp://localhost:5150");
        req.send("This is a test.");
    }

    auto t = new Thread(&_thread);
    auto router = Socket(SocketType.router);
    router.bind("tcp://*:5150");
    t.start();

    auto msg = Frame();
    router.receive(msg);
    writeln(msg.data.idup);
    assert(router.more);
    router.receive(msg);
    writeln(msg.data.idup);
    assert(router.more);
    router.receive(msg);
    writeln(cast(string)msg.data.idup);
    assert(!router.more);

    t.join();
}
```
Interestingly enough, this issue doesn't show up when the REQ is on the main thread and the ROUTER is in the child thread. Additionally, if you drop the threaded bit and just call `_thread`, the issue also appears. Placing it inline like so:
```
auto router = Socket(...);
auto req = Socket(...);

router.bind(...);
req.connect(...);

req.send(...);
auto msg = Frame();
```
causes it to work again.

**Comment by kyllingstad** [comment]
I'll look at the test case, but the fact that the problem goes away when you switch the sockets between the threads indicates that this is not a problem with Deimos::ZeroMQ. These bindings do not contain any program logic; they're just a D version of the C header file `zmq.h`, and only contain numerical constants and function declarations. If there was anything wrong with those, it would presumably be wrong regardless of how or when the functions are called.

*zmqd*, on the other hand, does add some program logic on top of these. It would be better to test this by comparing a C program and an equivalent D program using the Deimos bindings directly.

One thing which could lead to the problem you mention is the fact that *zmqd* [sets the sockets' LINGER period to zero by default](http://kyllingstad.github.io/zmqd/zmqd_v1.1.html#Socket). This means that when your `_thread()` function exits and the `req` object is destroyed, the socket may be closed before it's had time to send the message. See the [ZMQ_LINGER documentation](http://api.zeromq.org/4-2:zmq-setsockopt#toc24) for details.

**Comment by Web-eWorks** [comment]
False alarm, the 0 LINGER was it. Thanks for the help.
