### ISSUE TITLE
Needs new tag to pick up latest Windows fix

### ISSUE THREAD

**Issue by atilaneves** [D-Programming-Deimos/ZeroMQ#30]
Otherwise the `zmqd` package won't build on Windows.

**Comment by CyberShadow** [comment]
@atilaneves I've added you to Team Deimos, so you should now be able to push the tag yourself :)

**Comment by kyllingstad** [comment]
Please do. But you should rather move the last version tag, not create a new one. The tags track upstream versions.

**Comment by atilaneves** [comment]
Done.

**Comment by kyllingstad** [comment]
Thanks!
