### ISSUE TITLE
tryReceive throws an exception on Windows

### ISSUE THREAD

**Issue by atilaneves** [D-Programming-Deimos/ZeroMQ#32]
`tryReceive` throws an exception on Windows when there is no data to be read. The reason is that on [this line](https://github.com/kyllingstad/zmqd/blob/95ca359b9dc29c9430b121a87db3a688c17adb51/src/zmqd.d#L480) it uses `core.stdc.errno.errno` instead of [zeromq's own errno](http://api.zeromq.org/4-1:zmq-errno) which is specifically to deal with Windows.

**Comment by atilaneves** [comment]
Wrong repository, sorry.

**Comment by kyllingstad** [comment]
No, I'm pretty sure you have the right repository. :) At least, you point to what appears to be a real bug in zmqd, and it should be fixed here.

**Comment by kyllingstad** [comment]
ah, wait, no, you don't. This is the deimos/zeromq repo. I made the same mistake :D
